// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package Backend

import (
	"time"
)

type NewPost struct {
	Title string `json:"title"`
	Text  string `json:"text"`
}

type Post struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	Text      string    `json:"text"`
	Date      time.Time `json:"date"`
	Published bool      `json:"published"`
	Author    *User     `json:"author"`
}

type User struct {
	ID       string `json:"id"`
	Username string `json:"username"`
	Password string `json:"password"`
	Fullname string `json:"fullname"`
}
